sudo: true
language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.3
matrix:
  include:
    - elixir: 1.8.1
      otp_release: 21.3
script:
  - mix analyze --non-interactive
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
